<?php
/**
 * Implements hook_help().
 *
 * Displays help and module information.
 *
 * @param path
 *   Which path of the site we're using to display help
 * @param arg
 *   Array that holds the current path as returned from arg() function
 */

  define('OLDBASE', 'tmp_prod_migration');

function drupal_migrate_help($path, $arg) {
	switch ($path) {
		case "admin/help#drupal_migrate":
			return '<p>' . t("A module that allows migrates users, taxonomies, content from Drupal site (current version)") . '</p>';
			break;
	}
}


